test:
	g++ -o driver test.cpp Pinball.cpp

real:
	g++ -o driver myDriver.cpp Pinball.cpp words.h

test1:	
	g++ -o driver smallTest.cpp Pinball.cpp

test2:
	g++ -o driver mediumTest.cpp Pinball.cpp

run:
	driver